***Notebook For Data Cleaning***

importing several libraries/modules and perform necessary setups.

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from dateutil import parser
import zipfile
import os

Giving the path to the csv file which needs to be preprocessed.

In [2]:
run_locally = False
if run_locally:
    dataset_path = 'data/Airline_review.csv'
else:
    dataset_path = 'C:/Users/cvish/Desktop/Gemini/data/Airline_review.csv'
    
df = pd.read_csv(dataset_path, index_col=0)
df.head()

,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no

In [3]:
# Parse the date strings using dateutil.parser.parse
df['review_datetime'] = df['Review Date'].apply(lambda x: parser.parse(x))

In [4]:
df.head()

,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended,review_datetime
0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes,2019-11-11
1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no,2019-06-25
2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no,2019-06-25
3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no,2019-09-28
4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,2019-09-24

In [5]:
df.describe()

,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,review_datetime
count,19016.000000,18911.000000,14500.000000,18378.000000,10829.000000,5920.000000,22105.000000,23171
mean,2.618374,2.871609,2.553586,2.353738,2.179056,1.780405,2.451165,2019-04-11 06:37:33.126753280
min,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2002-01-06 00:00:00
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2017-01-14 12:00:00
50%,3.000000,3.000000,2.000000,1.000000,2.000000,1.000000,2.000000,2020-01-13 00:00:00
75%,4.000000,4.000000,4.000000,4.000000,3.000000,2.000000,4.000000,2022-12-08 00:00:00
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,2023-07-27 00:00:00
std,1.464840,1.604631,1.526314,1.595747,1.488839,1.318800,1.594155,NaN

We import several modules from the Natural Language Toolkit (NLTK) library, which is commonly used for natural language processing (NLP) tasks:

1. `import nltk`: Imports the NLTK library, a powerful tool for working with human language data.

2. `from nltk.sentiment.vader import SentimentIntensityAnalyzer`: Imports the `SentimentIntensityAnalyzer` class from the VADER (Valence Aware Dictionary and sEntiment Reasoner) module in NLTK. VADER is a lexicon and rule-based sentiment analysis tool that is specifically attuned to sentiments expressed in social media.

3. `from nltk.corpus import stopwords`: Imports the `stopwords` corpus from NLTK, which contains a list of common words that are often considered irrelevant in text analysis.

4. `from nltk.tokenize import word_tokenize`: Imports the `word_tokenize` function from NLTK, which tokenizes text into words or tokens.

5. `from nltk.stem import WordNetLemmatizer`: Imports the `WordNetLemmatizer` class from NLTK, which is used for lemmatizing words to their base or dictionary form.

- `names`: Contains a list of names.
- `stopwords`: Contains a list of common stopwords.
- `vader_lexicon`: Contains the lexicon used by VADER for sentiment analysis.
- `punkt`: Contains pre-trained models for tokenization.
- `wordnet`: Contains the WordNet lexical database, which is used for various NLP tasks such as lemmatization.

This ensures that the necessary NLTK resources are available for subsequent NLP tasks.

In [6]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer


# download nltk corpus (first time only)
nltk.download([
"names",
"stopwords",
"vader_lexicon",
"punkt",
"wordnet"
])

[nltk_data] Downloading package names to
[nltk_data]     C:\Users\cvish\AppData\Roaming\nltk_data...
[nltk_data]   Package names is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\cvish\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\cvish\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\cvish\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\cvish\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

We ensure that the contents of the `wordnet.zip` file are extracted to the appropriate directory, making them accessible for subsequent operations.

In [ ]:
# Define the paths
zip_file_path = "/usr/share/nltk_data/corpora/wordnet.zip"
extracted_folder_path = "/usr/share/nltk_data/corpora/"

# Unzip the file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_folder_path)

# Confirm extraction
print("File extracted successfully to:", extracted_folder_path)

The `preprocess_text` function preprocesses text data by performing tokenization, stop word removal, and lemmatization. It takes an input text string, tokenizes it into individual words, removes common English stop words, lemmatizes the remaining tokens to their base or dictionary form, and then joins the tokens back into a single string.

In [ ]:
# create preprocess_text function
def preprocess_text(text):

    # Tokenize the text
    tokens = word_tokenize(text.lower())

    # Remove stop words
    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]


    # Lemmatize the tokens
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]

    # Join the tokens back into a string
    processed_text = ' '.join(lemmatized_tokens)
    return processed_text

start_time = dt.datetime.now()
print("Started text preprocessing at ", start_time)
df['Review'] = df['Review'].apply(preprocess_text)
end_time = dt.datetime.now()
elapsed_time = end_time - start_time
print("Finished text preprocessing at ", end_time)
print ("Text preprocessing completed. Elapsed time: ", elapsed_time)

In [9]:
df

,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended,review_datetime
0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes,2019-11-11
1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no,2019-06-25
2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no,2019-06-25
3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,Frankfurt to Pristina,September 2019,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no,2019-09-28
4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,2019-09-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23166,ZIPAIR,1,"""customer service is terrible""",5th July 2022,False,Bangkok to Tokyo. I’ve flown many low cost ai...,NaN,Couple Leisure,Economy Class,Bangkok to Tokyo,June 2022,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no,2022-07-05
23167,ZIPAIR,1,"""Avoid at all costs""",1st June 2022,True,Avoid at all costs. I booked flights to go f...,NaN,Solo Leisure,Economy Class,Singapore to Tokyo,June 2022,NaN,NaN,NaN,NaN,NaN,NaN,1.0,no,2022-06-01
23168,ZIPAIR,3,"""Will not recommend to anyone""",31st May 2022,True,Flight was leaving at 23.15 and after an hou...,NaN,Business,Economy Class,Bangkok to Tokyo,May 2022,2.0,4.0,2.0,1.0,NaN,NaN,2.0,no,2022-05-31
23169,ZIPAIR,6,"""It was immaculately clean""",23rd May 2022,True,Zipair is JAL’s budget airline. They don’t ha...,Dreamliner,Business,Business Class,Tokyo to Los Angeles,May 2022,3.0,4.0,3.0,1.0,2.0,5.0,5.0,yes,2022-05-23
23170,ZIPAIR,1,"""lost all of our money with no refund""",20th May 2022,True,They lied about connection in Narita and we ...,NaN,Solo Leisure,Economy Class,Singapore to Tokyo,May 2022,NaN,NaN,NaN,1.0,NaN,NaN,1.0,no,2022-05-20

In [ ]:
df.describe()

,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,review_datetime
count,19016.000000,18911.000000,14500.000000,18378.000000,10829.000000,5920.000000,22105.000000,23171
mean,2.618374,2.871609,2.553586,2.353738,2.179056,1.780405,2.451165,2019-04-11 06:37:33.126753280
min,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2002-01-06 00:00:00
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2017-01-14 12:00:00
50%,3.000000,3.000000,2.000000,1.000000,2.000000,1.000000,2.000000,2020-01-13 00:00:00
75%,4.000000,4.000000,4.000000,4.000000,3.000000,2.000000,4.000000,2022-12-08 00:00:00
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,2023-07-27 00:00:00
std,1.464840,1.604631,1.526314,1.595747,1.488839,1.318800,1.594155,NaN

In [ ]:
#Check the contents of the Review column to ensure that all the operations have been performed correctly
df['Review']

0          Moroni to Moheli. Turned out to be a pretty ...
1         Moroni to Anjouan. It is a very small airline...
2          Anjouan to Dzaoudzi. A very small airline an...
3          Please do a favor yourself and do not fly wi...
4         Do not book a flight with this airline! My fr...
                               ...
23166     Bangkok to Tokyo. I’ve flown many low cost ai...
23167      Avoid at all costs. I booked flights to go f...
23168      Flight was leaving at 23.15 and after an hou...
23169     Zipair is JAL’s budget airline. They don’t ha...
23170      They lied about connection in Narita and we ...
Name: Review, Length: 23171, dtype: object

**Tackling the NULL Values problem**

In [ ]:
df.isnull().sum()

Airline Name                  0
Overall_Rating                0
Review_Title                  0
Review Date                   0
Verified                      0
Review                        0
Aircraft                  16042
Type Of Traveller          3738
Seat Type                  1096
Route                      3828
Date Flown                 3754
Seat Comfort               4155
Cabin Staff Service        4260
Food & Beverages           8671
Ground Service             4793
Inflight Entertainment    12342
Wifi & Connectivity       17251
Value For Money            1066
Recommended                   0
review_datetime               0
dtype: int64

For columns with integer values we fill the empty values with the mean of the non-empty values (imputation) and wherever the values are strings we have replaced the values with **"Unknown"**

In [ ]:
# Impute null values in 'Aircraft' column with 'Unknown'
df['Aircraft'].fillna('Unknown', inplace=True)

# Impute null values in 'Type Of Traveller' column with 'Unknown'
df['Type Of Traveller'].fillna('Unknown', inplace=True)

# Impute null values in 'Seat Type' column with 'Unknown'
df['Seat Type'].fillna('Unknown', inplace=True)

# Impute null values in 'Route' column with 'Unknown'
df['Route'].fillna('Unknown', inplace=True)

# Impute null values in 'Date Flown' column with 'Unknown'
df['Date Flown'].fillna('Unknown', inplace=True)

# Impute null values in 'Seat Comfort' column with the mean of non-null values
mean_seat_comfort = df['Seat Comfort'].mean()
df['Seat Comfort'].fillna(int(mean_seat_comfort), inplace=True)

css = df['Cabin Staff Service'].mean()
df['Cabin Staff Service'].fillna(int(css), inplace=True)

fab = df['Food & Beverages'].mean()
df['Food & Beverages'].fillna(int(fab), inplace=True)

gs = df['Ground Service'].mean()
df['Ground Service'].fillna(int(gs), inplace=True)

# Impute null values in 'Value For Money' column with the mean of non-null values
mean_value_for_money = df['Value For Money'].mean()
df['Value For Money'].fillna(mean_value_for_money, inplace=True)

# Impute null values in 'Inflight Entertainment' column with 'Not Available'
df['Inflight Entertainment'].fillna('Not Available', inplace=True)

# Impute null values in 'Wifi & Connectivity' column with 'Not Available'
df['Wifi & Connectivity'].fillna('Not Available', inplace=True)

# You can continue imputing null values for other columns as needed

# Display the first few rows of the DataFrame to verify changes
print(df.head())

    Airline Name Overall_Rating                           Review_Title  \
0    AB Aviation              9                "pretty decent airline"
1    AB Aviation              1                   "Not a good airline"
2    AB Aviation              1         "flight was fortunately short"
3  Adria Airways              1    "I will never fly again with Adria"
4  Adria Airways              1  "it ruined our last days of holidays"

           Review Date  Verified  \
0   11th November 2019      True
1       25th June 2019      True
2       25th June 2019      True
3  28th September 2019     False
4  24th September 2019      True

                                              Review       Aircraft  \
0    Moroni to Moheli. Turned out to be a pretty ...        Unknown
1   Moroni to Anjouan. It is a very small airline...           E120
2    Anjouan to Dzaoudzi. A very small airline an...  Embraer E120
3    Please do a favor yourself and do not fly wi...        Unknown
4   Do not book a flight with this airline! My fr...        Unknown

  Type Of Traveller      Seat Type                             Route  \
0      Solo Leisure  Economy Class                  Moroni to Moheli
1      Solo Leisure  Economy Class                 Moroni to Anjouan
2      Solo Leisure  Economy Class               Anjouan to Dzaoudzi
3      Solo Leisure  Economy Class             Frankfurt to Pristina
4    Couple Leisure  Economy Class  Sofia to Amsterdam via Ljubljana

       Date Flown  Seat Comfort  Cabin Staff Service  Food & Beverages  \
0   November 2019           4.0                  5.0               4.0
1       June 2019           2.0                  2.0               1.0
2       June 2019           2.0                  1.0               1.0
3  September 2019           1.0                  1.0               2.0
4  September 2019           1.0                  1.0               1.0

   Ground Service Inflight Entertainment Wifi & Connectivity  Value For Money  \
0             4.0          Not Available       Not Available              3.0
1             1.0          Not Available       Not Available              2.0
2             1.0          Not Available       Not Available              2.0
3             1.0          Not Available       Not Available              1.0
4             1.0                    1.0                 1.0              1.0

  Recommended review_datetime
0         yes      2019-11-11
1          no      2019-06-25
2          no      2019-06-25
3          no      2019-09-28
4          no      2019-09-24

C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Aircraft'].fillna('Unknown', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Type Of Traveller'].fillna('Unknown', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Seat Type'].fillna('Unknown', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Route'].fillna('Unknown', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date Flown'].fillna('Unknown', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Seat Comfort'].fillna(int(mean_seat_comfort), inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin Staff Service'].fillna(int(css), inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Food & Beverages'].fillna(int(fab), inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ground Service'].fillna(int(gs), inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Value For Money'].fillna(mean_value_for_money, inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:34: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Inflight Entertainment'].fillna('Not Available', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Inflight Entertainment'].fillna('Not Available', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Wifi & Connectivity'].fillna('Not Available', inplace=True)
C:\Users\cvish\AppData\Local\Temp\ipykernel_29604\3049379475.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Wifi & Connectivity'].fillna('Not Available', inplace=True)

In [ ]:
df.isnull().sum()

Airline Name              0
Overall_Rating            0
Review_Title              0
Review Date               0
Verified                  0
Review                    0
Aircraft                  0
Type Of Traveller         0
Seat Type                 0
Route                     0
Date Flown                0
Seat Comfort              0
Cabin Staff Service       0
Food & Beverages          0
Ground Service            0
Inflight Entertainment    0
Wifi & Connectivity       0
Value For Money           0
Recommended               0
review_datetime           0
dtype: int64

In [ ]:
df.head()

,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended,review_datetime
0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,Unknown,Solo Leisure,Economy Class,Moroni to Moheli,November 2019,4.0,5.0,4.0,4.0,Not Available,Not Available,3.0,yes,2019-11-11
1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,June 2019,2.0,2.0,1.0,1.0,Not Available,Not Available,2.0,no,2019-06-25
2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,June 2019,2.0,1.0,1.0,1.0,Not Available,Not Available,2.0,no,2019-06-25
3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,Unknown,Solo Leisure,Economy Class,Frankfurt to Pristina,September 2019,1.0,1.0,2.0,1.0,Not Available,Not Available,1.0,no,2019-09-28
4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,Unknown,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,September 2019,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,2019-09-24

**Feature Engineering**

Adding a new feature called `Sentiment` which contains values `Positive` or `Negative` to further enhance model's knowledge on happiness level of the customer on the specific airline

In [ ]:
df['Sentiment'] = df['Recommended'].apply(lambda x: 'Positive' if x == 'yes' else 'Negative')

In [ ]:
df.isnull().sum()

Airline Name              0
Overall_Rating            0
Review_Title              0
Review Date               0
Verified                  0
Review                    0
Aircraft                  0
Type Of Traveller         0
Seat Type                 0
Route                     0
Date Flown                0
Seat Comfort              0
Cabin Staff Service       0
Food & Beverages          0
Ground Service            0
Inflight Entertainment    0
Wifi & Connectivity       0
Value For Money           0
Recommended               0
review_datetime           0
Sentiment                 0
dtype: int64

Here we add another column called `Location Entities` which contains arrays of location values extracted from `Reviews` using **Named Entity Recognition(NER)** techinques

In [ ]:
import spacy

In [ ]:
# Load spaCy model for English
nlp = spacy.load("en_core_web_sm")
data=df['Review']
def extract_location_entities(review):
    doc = nlp(review)
    locations = [ent.text for ent in doc.ents if ent.label_ == "GPE"]  # GPE: geopolitical entity
    return locations
# Apply NER to each review and store the extracted entities in a new column
df["Location Entities"] = df["Review"].apply(extract_location_entities)

In [ ]:
df['Location Entities']

0                                        [Moheli]
1                                              []
2                                       [Comoros]
3                                        [Munich]
4                              [Sofia, Amsterdam]
                           ...
23166    [Bangkok, Tokyo, Thailand, Japan, Japan]
23167                          [Singapore, Tokyo]
23168                                   [Bangkok]
23169                                          []
23170                            [Narita, Narita]
Name: Location Entities, Length: 23171, dtype: object

Also I created a column `Travel Day` to indicate the day on which they travelled to make the model understand if there is a relation between travelling on Weekdays or on Weekends indicated by column `Weekend Travel`

In [ ]:
# Replace invalid entries in 'Date Flown' column with NaN
df['Date Flown'] = df['Date Flown'].replace('Unknown', pd.NaT)

# Convert 'Date Flown' column to datetime with a specific format, ignoring NaN values
df['Date Flown'] = pd.to_datetime(df['Date Flown'], format='%B %Y', errors='coerce')

# Create a new column 'Travel Day' to extract the day of the week
df['Travel Day'] = df['Date Flown'].dt.day_name()

# Create a new column 'Weekend Travel' to indicate whether the travel day is a weekend or not
df['Weekend Travel'] = df['Travel Day'].apply(lambda x: 'Weekend' if x in ['Saturday', 'Sunday'] else 'Weekday')

In [ ]:
df.head()

,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,...,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended,review_datetime,Sentiment,Location Entities,Travel Day,Weekend Travel
0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,Unknown,Solo Leisure,Economy Class,Moroni to Moheli,...,4.0,Not Available,Not Available,3.0,yes,2019-11-11,Positive,[Moheli],Friday,Weekday
1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,...,1.0,Not Available,Not Available,2.0,no,2019-06-25,Negative,[],Saturday,Weekend
2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,...,1.0,Not Available,Not Available,2.0,no,2019-06-25,Negative,[Comoros],Saturday,Weekend
3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,Unknown,Solo Leisure,Economy Class,Frankfurt to Pristina,...,1.0,Not Available,Not Available,1.0,no,2019-09-28,Negative,[Munich],Sunday,Weekend
4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,Unknown,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,...,1.0,1.0,1.0,1.0,no,2019-09-24,Negative,"[Sofia, Amsterdam]",Sunday,Weekend

Then I made another column `Review Length to Rating Ratio`  to measure the ratio of **Review Length to Rating ratio** to knw how ratings affected the review length. The more happier customers generally tend to add more to the reviews suugesting a more happy score.

In [ ]:
df['Overall_Rating'] = pd.to_numeric(df['Overall_Rating'], errors='coerce')

# Calculate the length of each review
df['Review Length'] = df['Review'].apply(len)

# Create a new column for the Review Length to Rating Ratio
df['Review Length to Rating Ratio'] = df['Review Length'] / df['Overall_Rating']

In [ ]:
df.head()

,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,...,Wifi & Connectivity,Value For Money,Recommended,review_datetime,Sentiment,Location Entities,Travel Day,Weekend Travel,Review Length,Review Length to Rating Ratio
0,AB Aviation,9.0,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,Unknown,Solo Leisure,Economy Class,Moroni to Moheli,...,Not Available,3.0,yes,2019-11-11,Positive,[Moheli],Friday,Weekday,352,39.111111
1,AB Aviation,1.0,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,...,Not Available,2.0,no,2019-06-25,Negative,[],Saturday,Weekend,689,689.000000
2,AB Aviation,1.0,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,...,Not Available,2.0,no,2019-06-25,Negative,[Comoros],Saturday,Weekend,405,405.000000
3,Adria Airways,1.0,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,Unknown,Solo Leisure,Economy Class,Frankfurt to Pristina,...,Not Available,1.0,no,2019-09-28,Negative,[Munich],Sunday,Weekend,734,734.000000
4,Adria Airways,1.0,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,Unknown,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,...,1.0,1.0,no,2019-09-24,Negative,"[Sofia, Amsterdam]",Sunday,Weekend,597,597.000000

Lastly, I have conatenated all the columns into one column  and made it into a new `csv` file to be sent for **OpenAI Embeddings Vectorization**

In [ ]:
# Concatenate all columns into a new column named 'concatenated'
df['concatenated'] = df.apply(lambda row: ' '.join(row.astype(str)), axis=1)

# Create a new DataFrame containing only the 'concatenated' column
new_df = df[['concatenated']]

# Generate a new CSV file containing only the 'concatenated' column
new_df.to_csv('concatenated_data.csv', index=False)